details:
    page_title: Tipboard exemple
layout:
    - row_1_of_2:
#        - col_1_of_4:
#            - tile_template: text
#              tile_id: txt_ex
#              title: text
#              classes:

        - col_1_of_4:
            - tile_template: pie_chartjs
              tile_id: pie_chartjs_ex
              title: pie_chartjs
              classes:

        - col_1_of_4:
            - tile_template: cumulative_flow
              tile_id: cf_ex
              title: cumul_flow
              classes:

        - col_1_of_4:
            - tile_template: simple_percentage
              tile_id: sp_ex
              title: percentage
              classes:

#            - tile_template: listing
#              tile_id: listing_ex
#              title: listing
#              classes:

        - col_1_of_4:
            - tile_template: bar_chartjs
              tile_id: barjs_ex
              title: barjs_chart
              classes:

#            - tile_template: fancy_listing   Hided cause of flip bug, but need to keep update tile and test it
#              tile_id: fancy_ex
#              title: fancyListing
#              classes:

    - row_1_of_2:
        - col_1_of_4:
            - tile_template: line_chartjs
              tile_id: line_chartjs_ex
              title: line_chartjs
              classes:

        - col_1_of_4:
            - tile_template: just_value
              tile_id: jv_ex
              title: just_value
              classes:

        - col_1_of_4:
            - tile_template: big_value
              tile_id: bv_ex
              title: big_value
              classes:

        - col_1_of_4:
            - tile_template: norm_chart
              tile_id: norm_ex
              title: normchart
              classes: