details:
    page_title: Tipboard exemple
layout:
    - row_1_of_2:

        - col_1_of_4:
            - tile_template: pie_chartjs
              tile_id: pie_chartjs_ex
              title: pie chart
              classes:

        - col_1_of_4:
            - tile_template: cumulative_flowjs
              tile_id: cfjs_ex
              title: cumulflow
              classes:

        - col_1_of_4:
            - tile_template: simple_percentage
              tile_id: sp_ex
              title: Percentage
              classes:

        - col_1_of_4:
            - tile_template: bar_chartjs
              tile_id: barjs_ex
              title: bar tile's
              classes:


    - row_1_of_2:
        - col_1_of_4:
            - tile_template: line_chartjs
              tile_id: line_chartjs_ex
              title: line tile's
              classes:

        - col_1_of_4:
            - tile_template: just_value
              tile_id: jv_ex
              title: Just value
              classes:

        - col_1_of_4:
            - tile_template: big_value
              tile_id: bv_ex
              title: Big value
              classes:

        - col_1_of_4:
            - tile_template: norm_chartjs
              tile_id: normjs_ex
              title: norm tile's
              classes:

#        - col_1_of_4:
#            - tile_template: text
#              tile_id: txt_ex
#              title: text
#              classes:

#            - tile_template: listing
#              tile_id: listing_ex
#              title: listing
#              classes:

#            - tile_template: fancy_listing   Hided cause of flip bug, but need to keep update tile and test it
#              tile_id: fancy_ex
#              title: fancyListing
#              classes:
