details:
    page_title: Tipboard exemple
layout:
    - row_1_of_2:
        - col_1_of_4 flip-time-5:
            - tile_template: text
              tile_id: txt_ex
              title: text
              classes:

            - tile_template: pie_chart
              tile_id: pie_ex
              title: pie_chart
              classes:

        - col_1_of_4  flip-time-10:
            - tile_template: line_chart
              tile_id: line_ex
              title: line_chart
              classes:

            - tile_template: cumulative_flow
              tile_id: cf_ex
              title: cumul_flow
              classes:

        - col_1_of_4 flip-time-10:
            - tile_template: simple_percentage
              tile_id: sp_ex
              title: percentage
              classes:

            - tile_template: listing
              tile_id: listing_ex
              title: listing
              classes:

        - col_1_of_4  flip-time-10:
            - tile_template: bar_chart
              tile_id: bar_ex
              title: bar_chart
              classes:

            - tile_template: fancy_listing
              tile_id: fancy_ex
              title: fancyListing
              classes:

    - row_1_of_2:
        - col_1_of_4:
            - tile_template: line_chartjs
              tile_id: line_charjs_ex
              title: line_chartjs
              classes:

        - col_1_of_4:
            - tile_template: pie_chartjs
              tile_id: pie_charjs_ex
              title: line_chartjs
              classes:

        - col_1_of_4 flip-time-10:
            - tile_template: just_value
              tile_id: jv_ex
              title: just_value
              classes:

            - tile_template: big_value
              tile_id: bv_ex
              title: big_value
              classes:

        - col_1_of_4:
            - tile_template: norm_chart
              tile_id: norm_ex
              title: normchart
              classes:


#il faut ajouter une tile line_chartjs
#ajouter le .js dans l'import html
#verifier qu'il a bien été download
#qu'il a bien registeNewFonction
#essayer de lui envoyer de la data
#ensuite faut essayer de voir un console log avec la data
#
#
#Si ca marche pasfait une autre tile sans la lib jqplot
