details:
    page_title: Dashboard 1
    color_mode: white
layout:
    - row_1_of_1:

        - col_1_of_1:
            - tile_template: iframe
              tile_id: iframe_ex
              title: Exemple Iframe
