details:
    page_title: Streamboard
    color_mode: black
layout:
    - row weight-2:

        - col weight-2:
            - tile_template: stream
              tile_id: stream_ex
              title: Stream

        - col:
            - tile_template: stream
              tile_id: stream_ex1
              title: Stream1

        - col:
            - tile_template: stream
              tile_id: stream_ex2
              title: Stream2


    - row:

        - col:
            - tile_template: stream
              tile_id: stream_ex4
              title: Exemple Stream 4

        - col:
            - tile_template: stream
              tile_id: stream_ex5
              title: Stream5

        - col:
            - tile_template: stream
              tile_id: stream_ex6
              title: Stream6

    - row:

        - col:
            - tile_template: stream
              tile_id: stream_ex7
              title: Stream7


        - col:
            - tile_template: stream
              tile_id: stream_ex3
              title: Stream3


        - col:
            - tile_template: stream
              tile_id: stream_ex8
              title: Stream8
