stages:
  - docker-image

include:
  - project: "gitlab-ci-lib"
    file: "Docker.gitlab-ci.yml"

docker-image-dev:
  extends: .docker-image
  variables:
    DOCKER_HUB_URL: ${DOCKER_HUB_DEV_URL}

docker-image-release:
  extends: .docker-image
  variables:
    DOCKER_HUB_URL: ${DOCKER_HUB_RELEASE_URL}
  only:
    - tags
