image: docker:latest

services:
  - docker:dind

stages:
- build
- test
- integration
- pkg_release
- deploy

variables:
  IMAGE_TAG: docker.pkg.github.com/the-maux/tipboard/tipboard:latest-gitlab

build_img:
  stage: build
  script:
    - docker build -t tipboard:untested .

test:
  stage: test
  script:
    - docker run --entrypoint src/manage.py tipboard:untested test
    - docker tag tipboard:untested tipboard:dev

ci_github_dev:
  stage: integration
  script:
    - docker login -u themaux -p ${CI_DOCKER_HUB} docker.io
    - docker tag tipboard:dev docker.pkg.github.com/the-maux/tipboard/tipboard:dev
    - docker push docker.pkg.github.com/the-maux/tipboard/tipboard:dev
  only: ['develop']

ci_github_master:
  stage: pkg_release
  script:
    - docker login -u themaux -p ${CI_DOCKER_HUB} docker.io
    - docker tag tipboard:dev docker.pkg.github.com/the-maux/tipboard/tipboard:latest
    - docker push docker.pkg.github.com/the-maux/tipboard/tipboard:latest
  only: ['master']

deploy_aws:
  stage: integration
  script:
    - docker run --entrypoint src/manage.py tipboard:latest test

  only: ['gitlab-cd/aws']
