image: docker:latest

services:
  - docker:dind

stages:
- build
- test
- integration
- deploy

variables:
  IMAGE_TAG: docker.pkg.github.com/the-maux/tipboard/tipboard:latest-gitlab

build_img:
  stage: build
  script:
    - docker build -t tipboard:latest-gitlab .

test:
  stage: test
  script:
    - docker run --entrypoint src/manage.py tipboard:latest-gitlab test

integration_github:
  stage: integration
  script:
    - docker login -u themaux -p ${CI_DOCKER_HUB} docker.io
    - docker tag tipboard:latest-gitlab docker.pkg.github.com/the-maux/tipboard/tipboard:latest-gitlab
    - docker push docker.pkg.github.com/the-maux/tipboard/tipboard:latest-gitlab
  only: ['gitlab-ci/github-pkg']

#integration_pypi:
#  image: python:3.6-alpine
#  stage: integration
#  variables:
#    TWINE_USERNAME: $PYPI_USERNAME
#    TWINE_PASSWORD: $PYPI_PASSWORD
#  script:
#    - twine upload dist/*
#  only: ['gitlab-ci/pypi']

deploy_aws:
  stage: integration
  script:
    - docker run --entrypoint src/manage.py tipboard:latest-gitlab test

  only: ['gitlab-cd/aws']

#deploy_azure:
#  stage: integration
#  script:
#    - docker run --entrypoint src/manage.py tipboard:latest-gitlab test
#
#  only: ['gitlab-cd/azure', 'master/cd']
#
#deploy_openshift:
#  stage: integration
#  script:
#    - docker run --entrypoint src/manage.py tipboard:latest-gitlab test
#
#  only: ['gitlab-cd/openshift', 'master/cd']
