language: python
python:
  - "3.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install -r requirements.txt
script:
    - python3.7 src/manage.py test