details:
    page_title: Dashboard 1
layout:
    - row_1_of_1:

        - col_1_of_1:
            - tile_template: half_doughnut_chart
              tile_id: half_doughnut_ex42
              title: half_doughnut

