details:
    page_title: Tipboard exemple
    color_mode: white
layout:
    - row_1_of_2:

        - col_1_of_4 flip-time-1:
            - tile_template: doughnut_chart
              tile_id: doughnut_ex
              title: doughnut

            - tile_template: half_doughnut_chart
              tile_id: half_doughnut_ex
              title: half_doughnut

            - tile_template: pie_chart
              tile_id: pie_chartjs_ex
              title: pie chart

            - tile_template: polararea_chart
              tile_id: polararea_ex
              title: polar-area

            - tile_template: radar_chart
              tile_id: radar_ex
              title: radar chart

        - col_1_of_4 flip-time-2:

            - tile_template: vbar_chart
              tile_id: vbarjs_ex
              title: vertical bar

            - tile_template: bar_chart
              tile_id: barjs_ex
              title: bar tile's


        - col_1_of_4 flip-time-4:

            - tile_template: simple_percentage
              tile_id: sp_ex
              title: Percentage

            - tile_template: big_value
              tile_id: bv_ex
              title: Big value

            - tile_template: just_value
              tile_id: jv_ex
              title: Just value

            - tile_template: text
              tile_id: txt_ex
              title: text

            - tile_template: listing
              tile_id: listing_ex
              title: listing

        - col_1_of_4:
            - tile_template: iframe
              tile_id: iframe_ex
              title: Exemple Iframe

    - row_1_of_2:

        - col_1_of_4:
            - tile_template: linear_gauge_chart
              tile_id: lgauge_ex
              title: Linear gauge Iframe

        - col_1_of_4 weight-3:
            - tile_template: radial_gauge_chart
              tile_id: rgauge_ex
              title: Radial gauge Iframe

        - col_1_of_4 weight-3:
            - tile_template: gauge_chart
              tile_id: gauge_ex
              title: Gauge Iframe

        - col_1_of_4 flip-time-3 weight-3:

            - tile_template: line_chart
              tile_id: line_chartjs_ex
              title: line tile's

            - tile_template: cumulative_flow
              tile_id: cfjs_ex
              title: cumulflow

            - tile_template: norm_chart
              tile_id: normjs_ex
              title: norm tile's


