details:
    page_title: Tipboard exemple
    color_mode: white
layout:
    - row_1_of_1:

        - col_1_of_8:

            - tile_template: big_value
              tile_id: jv_jenkins
              title: Jenkinsbv
              classes:

        - col_1_of_8:

            - tile_template: big_value
              tile_id: jv_nexusbv
              title: Nexus
              classes:

        - col_1_of_8:

            - tile_template: big_value
              tile_id: jv_kibanabv
              title: Kibana
              classes:

        - col_1_of_8:

            - tile_template: big_value
              tile_id: jv_rabiitbv
              title: RabbitMQ
              classes:

        - col_1_of_8:

            - tile_template: big_value
              tile_id: jv_jenkins2bv
              title: Jenkins
              classes:

        - col_1_of_8:

            - tile_template: big_value
              tile_id: jv_nexus2bv
              title: Nexus
              classes:

        - col_1_of_8:

            - tile_template: big_value
              tile_id: jv_kibana2bv
              title: Kibana
              classes:

        - col_1_of_8:

            - tile_template: big_value
              tile_id: jv_rabiit2bv
              title: RabbitMQ
              classes:
