details:
  page_title: Dashboard 1
  color_mode: black
layout:
  - row weight-5:

      - col weight-8:
          - tile_template: line_chart
            tile_id: line_chartjs_ex
            title: line tile's

      - col weight-2:
          - tile_template: linear_gauge_chart
            tile_id: lgauge_ex
            title: Linear gauge Iframe

  - row weight-3:

      - col flip-time-2 weight-2:

          - tile_template: doughnut_chart
            tile_id: doughnut_ex
            title: doughnut

          - tile_template: radial_gauge_chart
            tile_id: rgauge_ex
            title: Radial gauge Iframe

      - col weight-3:
          - tile_template: gauge_chart
            tile_id: gauge_ex
            title: Gauge Iframe
