details:
  page_title: Tipboard exemple
  color_mode: black
layout:
    - row weight-3:

        - col:
            - tile_template: half_doughnut_chart
              tile_id: half_doughnut_ex42
              title: doughnut

        - col flip-time-2 weight-3:
            - tile_template: cumulative_flow
              tile_id: cfjs_ex
              title: cumulflow

            - tile_template: line_chart
              tile_id: line_chartjs_ex
              title: line tile's

        - col:
            - tile_template: norm_chart
              tile_id: normjs_ex
              title: norm tile's

            - tile_template: polararea_chart
              tile_id: polararea_ex
              title: polar-area

        - col flip-time-2:
            - tile_template: bar_chart
              tile_id: barjs_ex
              title: bar tile's

            - tile_template: radar_chart
              tile_id: radar_ex
              title: radar chart

    - row weight-2:
        - col:
            - tile_template: just_value
              tile_id: jv_ex
              title: Just value 1

        - col:
            - tile_template: big_value
              tile_id: bv_ex
              title: Big value

        - col:
            - tile_template: just_value
              tile_id: jv_ex3
              title: Just value 3

        - col flip-time-2:
            - tile_template: simple_percentage
              tile_id: sp_ex
              title: Percentage

            - tile_template: listing
              tile_id: list_ex
              title: Listing
